import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumbs, ButtonLink, Container, CTABand, FAQList, StatusBadge } from "@/components/ui";
import { Check } from "@/components/icons";
import { faqs, programs } from "@/lib/content";

export function generateStaticParams() { return programs.map(p=>({slug:p.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=programs.find(x=>x.slug===slug);if(!p)return{};return{title:p.name,description:p.summary,alternates:{canonical:`/programs/${slug}`}}}
export default async function ProgramDetail({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const p=programs.find(x=>x.slug===slug); if(!p) notFound(); const crumbs={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://stemeducation.in"},{"@type":"ListItem",position:2,name:"Programs",item:"https://stemeducation.in/programs"},{"@type":"ListItem",position:3,name:p.name,item:`https://stemeducation.in/programs/${p.slug}`}]}; return <>
  <section className={`program-detail-hero accent-${p.accent}`}><Container><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Programs",href:"/programs"},{label:p.name}]}/><div className="program-detail-grid"><div><p className="eyebrow">{p.eyebrow}</p><h1>{p.name}</h1><p className="lede">{p.summary}</p><div className="hero-actions"><ButtonLink href="/contact?interest=partnership">Discuss this program</ButtonLink><ButtonLink href="/programs" kind="secondary">All programs</ButtonLink></div></div><div className="program-glyph" aria-hidden="true"><span>{p.name.slice(0,2).toUpperCase()}</span><i/><i/><i/><i/></div></div></Container></section>
  <section className="section"><Container><div className="detail-layout"><article className="prose"><p className="eyebrow">Program overview</p><h2>What this program is</h2><p>{p.summary} The final configuration is shaped through school consultation, a readiness review and a jointly agreed implementation plan.</p><h2>Who it is for</h2><p>{p.audience}. Specific grade bands, cohort sizes and inclusion requirements are confirmed during program design.</p><h2>Learning outcomes</h2><ul className="check-list">{p.outcomes.map(x=><li key={x}><Check/>{x}</li>)}</ul></article><aside className="detail-aside"><StatusBadge/><h2>Verification before proposal</h2><p>Curriculum mapping, grade bands, infrastructure, scale, timeline and cost require confirmation for each school context.</p><ButtonLink href="/contact" kind="text">Request a discovery call</ButtonLink></aside></div></Container></section>
  <section className="section soft-section"><Container><div className="two-col"><div><p className="eyebrow">What is included</p><h2>Components that support sustained use.</h2><p>Equipment or content is paired with practical enablement and a plan for continued use.</p></div><div className="component-list">{p.components.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Scope and specification awaiting organizational verification.</p></article>)}</div></div></Container></section>
  <section className="section"><Container><div className="two-col reverse"><div><p className="eyebrow">Implementation</p><h2>A phased path from readiness to review.</h2></div><ol className="timeline"><li><b>Discover</b><span>Assess learner needs, people, space and constraints.</span></li><li><b>Design</b><span>Agree the learning model, resources, safeguards and evidence.</span></li><li><b>Prepare</b><span>Set up the intervention and enable teachers or facilitators.</span></li><li><b>Support</b><span>Review use, resolve friction and strengthen practice.</span></li><li><b>Report</b><span>Share evidence against agreed indicators and next steps.</span></li></ol></div></Container></section>
  <section className="section detail-band"><Container><div><h2>Teacher training & support</h2><p>Enablement is designed around facilitation practice, safe use and realistic classroom routines.</p></div><div><h2>Curriculum alignment</h2><p>Activities can be mapped to relevant concepts; specific board claims remain subject to verification.</p></div><div><h2>Space requirements</h2><p>Readiness criteria depend on the selected components, learner cohort and school infrastructure.</p></div></Container></section>
  <section className="section"><Container><div className="detail-layout"><div><p className="eyebrow">Evidence and learning</p><h2>Impact evidence will be tied to program intent.</h2><p>Recommended indicators include access, participation, frequency of use, teacher practice and learner response. Baselines and outcome methods are agreed before implementation.</p></div><div className="placeholder-panel"><StatusBadge/><h3>Related case study</h3><p>A verified case study for {p.name} will appear here after organization approval.</p></div></div></Container></section>
  <section className="section faq-section"><Container><div><p className="eyebrow">Frequently asked</p><h2>Questions about {p.name}</h2></div><FAQList items={faqs.slice(1,5)}/></Container></section><CTABand title={`Explore a ${p.name} partnership.`}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbs)}}/>
  </>; }
