import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check } from "@/components/icons";
import { ButtonLink, Container, CTABand, FAQList, PrincipleCard, ProgramCard, SectionHeading, StatusBadge } from "@/components/ui";
import { cases, faqs, impactStats, principles, programs, regions } from "@/lib/content";
import { TestimonialSlider } from "@/components/testimonial-slider";

export default function HomePage() { return <>
  <section className="home-hero"><Container><div className="hero-copy"><p className="eyebrow">STEM learning for real-world India</p><h1>Making STEM learning <em>practical, inclusive</em> and future-ready.</h1><p className="lede">We work with schools, CSR organizations and communities to turn science and technology education into active, supported learning.</p><div className="hero-actions"><ButtonLink href="/contact?interest=partnership">Partner with us</ButtonLink><ButtonLink href="/programs" kind="secondary">Explore programs</ButtonLink></div><div className="hero-trust"><span><Check/> School-context first</span><span><Check/> Teacher-supported</span><span><Check/> Evidence-aware</span></div></div><figure className="hero-figure"><Image src="/stem-classroom.png" alt="Indian students working together on a practical electronics activity as their teacher guides them" fill priority sizes="(max-width: 900px) 100vw, 52vw"/><figcaption>Curiosity becomes capability when learners can test their ideas.</figcaption><div className="hero-label"><strong>Learn • Make • Reflect</strong><span>A practical cycle for deeper learning</span></div></figure></Container></section>
  <section className="trust-strip" aria-labelledby="trust-title"><Container><div className="trust-intro"><p className="eyebrow">Transparent by design</p><h2 id="trust-title">Impact claims belong with evidence.</h2><p>Verified organization figures will appear here with clear definitions and reporting periods.</p></div><div className="stat-grid">{impactStats.map(s => <article key={s.label}><strong>{s.value}</strong><span>{s.label}</span><small>{s.note}</small></article>)}</div></Container></section>
  <section className="section approach-section"><Container><SectionHeading eyebrow="Why this approach" title="Four principles. One stronger learning experience." body="The most useful STEM spaces combine active learning, prepared educators, inclusive participation and visible evidence." align="center"/><div className="principle-grid">{principles.map(p => <PrincipleCard key={p.title} {...p}/>)}</div></Container></section>
  <section className="section programs-section"><Container><div className="heading-row"><SectionHeading eyebrow="Program portfolio" title="Structured pathways for different learning needs." body="Explore practical programs for classrooms, laboratories and whole-school learning environments."/><ButtonLink href="/programs" kind="text">View all programs</ButtonLink></div><div className="program-grid">{programs.slice(0,6).map(p => <ProgramCard key={p.slug} program={p}/>)}</div></Container></section>
  <section className="section process-section"><Container><SectionHeading eyebrow="Partnership journey" title="From a stated need to an accountable program." body="A clear delivery path helps CSR and education teams align expectations early."/><ol className="process-grid">{[["01","Understand the need","Listen to schools, map constraints and agree the problem worth solving."],["02","Design the intervention","Define learners, program components, outcomes, safeguards and evidence."],["03","Implement and train","Prepare the space, resources and people needed for confident delivery."],["04","Measure and report","Review reach, participation, use and agreed outcome indicators."]].map(x => <li key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></li>)}</ol></Container></section>
  <section className="section impact-feature"><Container><div className="impact-copy"><p className="eyebrow">Impact, with context</p><h2>Numbers should explain progress—not decorate a page.</h2><p>Our reporting model is designed to connect activities with participation, practice and learning outcomes. Public figures will be added only after definitions and source periods are verified.</p><ButtonLink href="/impact" kind="secondary">View impact approach</ButtonLink></div><div className="impact-ledger">{impactStats.map((s,i) => <article key={s.label}><span>0{i+1}</span><div><strong>{s.label}</strong><StatusBadge/></div></article>)}</div></Container></section>
  <section className="section"><Container><SectionHeading eyebrow="Field notes" title="Case studies built around the problem, the work and the evidence." body="Named organizations and outcome claims remain unpublished until approved."/><div className="case-grid">{cases.map((c,i) => <article className="case-card" key={c.title}><div className={`case-art art-${i+1}`} aria-hidden="true"><span>Field note {String(i+1).padStart(2,"0")}</span></div><div><StatusBadge/><p className="eyebrow">{c.location}</p><h3>{c.title}</h3><dl><div><dt>Challenge</dt><dd>{c.challenge}</dd></div><div><dt>Outcome</dt><dd>{c.outcome}</dd></div></dl><Link className="text-link" href="/resources/case-studies">View case study framework <ArrowRight/></Link></div></article>)}</div></Container></section>
  <section className="section presence-feature"><Container><div><SectionHeading eyebrow="National presence" title="Local context, visible in every program decision." body="The presence directory will make verified regional availability easy to find without creating thin state pages."/><ButtonLink href="/presence" kind="secondary">Explore presence</ButtonLink></div><div className="region-list">{regions.map((r,i) => <Link key={r.name} href={`/presence#region-${i+1}`}><span>{String(i+1).padStart(2,"0")}</span><strong>{r.name}</strong><small>{r.states}</small><ArrowRight/></Link>)}</div></Container></section>
  <section className="section story-section"><Container><TestimonialSlider /></Container></section>
  <section className="section faq-section"><Container><div><SectionHeading eyebrow="Partnership questions" title="Useful answers before the first conversation."/><ButtonLink href="/resources/faqs" kind="text">View all FAQs</ButtonLink></div><FAQList items={faqs.slice(0,5)}/></Container></section>
  <CTABand/>
  </>; }
